name: Automate AAF Data
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Update
        run: python update_script.py

      - name: Save Changes
        run: |
          git config --global user.name 'AAF-Robot'
          git config --global user.email 'bot@github.com'
          git add database.json
          git commit -m "Fix: modern actions and data update" || exit 0
          git push
